commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("<int:pk>", views.listing_detail, name="listing_detail"),

    path("bid", views.bid, name="bid"),
    path("bid_options", views.bid_options, name="bid_options"),

    path("watchlist", views.watchlist_view, name="watchlist"),
    path("add_to_watchlist", views.add_to_watchlist, name="add_to_watchlist"),
    path("remove_from_watchlist", views.remove_from_watchlist, name="remove_from_watchlist"),

    path("category/<str:name>", views.show_category, name="category"),

    path("profile", views.profile, name="profile"),

    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator


class User(AbstractUser):
    pass


class Listing (models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg", upload_to="listing_pics")
    price = models.FloatField(default=1, validators=[MaxValueValidator(1000), MinValueValidator(0)])
    is_closed = models.BooleanField(default=False)

    # Category Field
    CLOTHING = "CL"
    SHOES = "SH"
    ACCESSORIES = "AC"
    OTHER = "OT"
    LISTING_CATEGORIES = [(CLOTHING, 'Clothing'), (SHOES, 'Shoes'), (ACCESSORIES, 'Accessories'), (OTHER, 'Other')]
    listing_categories = models.CharField(max_length=2, choices=LISTING_CATEGORIES, default=OTHER)


    def __str__ (self):
        return f"{self.title}"

class Comment (models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    comment_on = models.ForeignKey(Listing, on_delete=models.CASCADE, default=None)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # constraints = [
        #     models.UniqueConstraint(fields=['content'], name='unique_user_comment')
        # ]
        ordering = ['-created_at']

    def clean(self):
        # Check if the user already has a listing
        if self.pk is None and Comment.objects.filter(author=self.author).exists():
            raise ValidationError('A user can only have one comment.')

    def __str__ (self):
        return f"Comment made by {self.author} to {self.comment_on}"


class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    bid_on = models.ForeignKey(Listing, on_delete=models.CASCADE)
    bid_amount = models.IntegerField(default=1, validators=[MaxValueValidator(1000), MinValueValidator(0)])

    def __str__(self):
        return f"{self.bidder} bid ${self.bid_amount} on {self.bid_on}"

class Profile(models.Model):
    user =  models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} Profile"

class Watchlist(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.listing}"

commerce/auctions/forms.py
from django.db import models
from django import forms
from django.forms import fields, ModelForm, HiddenInput
from django.utils import timezone

from .models import Listing, User, Profile

class ListingForm(ModelForm):

    date = forms.DateTimeField(initial=timezone.now(), widget=forms.HiddenInput)
    author = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput)

    class Meta:
        model = Listing
        fields = ["title", "content", "date", "author", "image", "price", "listing_categories" ]
    

class BiddingForm(forms.Form):
    bid = forms.IntegerField()

class CommentForm(forms.Form):
    message = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 1, 'cols': 20}))

# -> Updating the Profile forms

# class UserUpdateForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['username', 'email']

# class ProfileUpdateForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ["image"]

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from .models import User, Listing, Watchlist, Bid, Profile, Comment
from .forms import ListingForm, BiddingForm, CommentForm


def index(request):
    listings = {"listings": list(reversed(Listing.objects.filter(is_closed=False)))}
    return render(request, "auctions/index.html", listings)


def profile(request):

    # if request.method == "POST":
    #     image_form = ProfileUpdateForm(request.POST, request.FILES)
    #     if image_form.is_valid():
    #         image_form.save() # Error: Integrity error Not null constraint failed , not fixed
    #         messages.success(request, "Image is updated.")
    #         return HttpResponseRedirect(reverse("profile"))

    user_profile = Profile.objects.filter(user=request.user).first()
    all_listings = Listing.objects.all()
    my_listings = []
    for listing in all_listings:
        if listing.author == request.user:
            my_listings.append(listing)
    
    # image_form = ProfileUpdateForm(instance=request.user.profile) 

    return render(request, "auctions/profile.html", {"profile": user_profile, "listings": my_listings, })


@login_required
def bid(request):
    if request.method == "POST":
        bid_amount = request.POST["bid"]
        listing_id = request.POST["id"]
        listing = Listing.objects.get(id=listing_id)
        current_listing_price = listing.price
        
        if int(bid_amount) < int(current_listing_price):
            messages.warning(request, f"Bid must be greater than current listing price")
            return HttpResponseRedirect(reverse("listing_detail", args=(listing_id,)))

        if not request.user.id == listing.author.id:
            listing.price = bid_amount
            listing.save()
        
            bid = Bid.objects.create(bidder=request.user, bid_on=listing, bid_amount=bid_amount)
            messages.success(request, f"Successfully bid ${bid_amount} on {listing}")
            return HttpResponseRedirect(reverse("listing_detail", args=(listing_id,)))
        else:
            messages.warning(request, f"You can't bid on your own listings")
            return HttpResponseRedirect(reverse("listing_detail", args=(listing_id,)))


def show_category(request, name):
    categories = Listing.LISTING_CATEGORIES 
    name = name.capitalize()
    matched_listings = []
    for category in categories:
        if category[1] == name:
            matched_listings = Listing.objects.filter(listing_categories=category[0])
    if matched_listings:
        return render(request, "auctions/category.html", {"listings": matched_listings}) 
    else:
        return render(request, "auctions/category.html", {"listings": matched_listings}) 


@login_required
def bid_options(request):
    option = request.POST["option"]

    # Convert option to boolean values
    if option == "True":
        option = True
    elif option == "False":
        option == False

    # Get the listing that user working on
    listing_id = request.POST["id"]
    listing = Listing.objects.get(id=listing_id)

    # Handle Open listing and Close listing
    if option == True:# Closing
        listing.is_closed = option
        listing.save()
        messages.success(request, f"{listing} now closed")
        # notify_the_win(request)
        return HttpResponseRedirect(reverse("listing_detail", args=(listing_id,)))
    else:# Opening
        listing.is_closed = option
        listing.save()
        messages.success(request, f"{listing} now opened")
        return HttpResponseRedirect(reverse("listing_detail", args=(listing_id,)))


@login_required
def watchlist_view(request):
    watchlist = Watchlist.objects.all().filter(customer=request.user)
    return render (request, "auctions/watchlist.html", {"watchlist": watchlist})


@login_required
def add_to_watchlist(request):
    if request.POST:

        # Get the current listing
        listing_id = request.POST["id"]
        listing = Listing.objects.filter(id=listing_id).first()

        if not request.user.id == listing.author.id:

            # Get my watchlist items
            all_watchlist_items = Watchlist.objects.all()
            my_watchlist_items = []
            for watchlist_item in all_watchlist_items:
                if watchlist_item.customer == request.user:
                    my_watchlist_items.append(watchlist_item.listing)

            # Only create a watchlist item if it is not in my watchlist
            if listing not in my_watchlist_items:
                watchlist = Watchlist.objects.create(customer=request.user, listing=listing)
                messages.success(request, f"{watchlist} added to watchlist.")
                return HttpResponseRedirect(reverse("listing_detail", args=(listing_id,)))

            else:
                messages.warning(request ,f"Already {listing} in your wishlist")
                return HttpResponseRedirect(reverse("listing_detail", args=(listing_id,)))
        else:
            messages.warning(request ,f"You can't add your own listings for wishlist. Try adding someone else listing.")
            return HttpResponseRedirect(reverse("listing_detail", args=(listing_id,)))


@login_required
def remove_from_watchlist(request):
    watchlist_id = request.POST["id"]
    watchlist_item = Watchlist.objects.get(id=watchlist_id)
    watchlist_item.delete()
    messages.success(request, f"{watchlist_item} removed successfully.")
    return HttpResponseRedirect(reverse("watchlist"))


@login_required
def create_listing(request):
    if request.method == "POST":
        form = ListingForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("author")
            messages.success(request, f"Listing created by {username}")
            return HttpResponseRedirect(reverse("index"))
        else:
            messages.warning(request, f"Price must be in between $1 and $1000")

    user = request.user
    data = {"author_id": user.id, "author": user} 
    form = ListingForm(initial=data)
    return render (request, "auctions/create_listing.html", {"form": form}) 


@login_required
def listing_detail(request, **kwargs):
    pk = kwargs.get('pk')
    if request.method == "POST": # comments
        author = request.user
        listing = Listing.objects.get(pk=pk) 
        content = request.POST["message"]

        comments = Comment.objects.filter(author=request.user, comment_on=listing)
        if comments:
            messages.warning(request, f"You already posted comment to this listing.")
            return HttpResponseRedirect(reverse("listing_detail", args=(listing.id,)))
        else:
            Comment.objects.create(content=content, author=author, comment_on=listing)

    try:
        listing = Listing.objects.get(pk=pk)
    except ObjectDoesNotExist:
        messages.warning(request, f"does not exist!")
        return HttpResponseRedirect(reverse("index"))
    else:
        current_listing_comments = Comment.objects.filter(comment_on=listing)
        commentForm = CommentForm()
        return render(request, "auctions/listing.html", {"listing": listing, "comments":current_listing_comments, "commentForm": CommentForm, })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

commerce/auctions/templates/auctions/category.html
{% extends 'auctions/layout.html' %}

{% block body %}
    {% if listings %}
        {% for listing in listings %}
            <article class="media content-section">
                <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ listing.author }}</a>
                    <small class="text-muted">{{ listing.date|date:"F d, Y" }}</small>
                    <small class="ml-3">Price: <b>${{ listing.price }}</b></small>
                    <small class="ml-3">Category: <b>{{ listing.get_listing_categories_display }}</b></small>
                </div>
                <h2><a class="article-title" href="{% url 'listing_detail' pk=listing.pk %}">{{ listing.title }}</a></h2>
                <p class="article-content">{{ listing.content }}</p>
                <img width=320 height=320 src="{{ listing.image.url }}" />
            </article>
        {% endfor %}
    {% else %}
        <h1>Empty</h1>
    {% endif %}

{% endblock %}

commerce/auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="content-sections">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Create</button>
        </div>
        {% if form.errors %}
        <ul>
            {% for field_errors in form.errors.values %}
            {% for error in field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
            {% endfor %}
        </ul>
        {% endif %}
    </form>
</div>



{% endblock body %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% for listing in listings %}
      {% if not listing.is_closed %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ listing.author }}</a>
              <small class="text-muted">{{ listing.date|date:"F d, Y" }}</small>
              <small class="ml-3">Price: <b>${{ listing.price|floatformat:2 }}</b></small>
              <!-- {{ person.get_gender_display }} -->
              <small class="ml-3">Category: <b>{{ listing.get_listing_categories_display }}</b></small>
            </div>
            <h2><a class="article-title" href="{% url 'listing_detail' pk=listing.pk %}">{{ listing.title }}</a></h2>
            <p class="article-content">{{ listing.content }}</p>
			<img width=320 height=320 src="{{ listing.image.url }}" />
          </div>
        </article>
        {% else %}
         <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ listing.author }}</a>
              <small class="text-muted">{{ listing.date|date:"F d, Y" }}</small>
              <small class="ml-3"><b>Closed</b></small>
            </div>
            <h2><a class="article-title" href="{% url 'listing_detail' pk=listing.pk %}">{{ listing.title }}</a></h2>
            <p class="article-content">{{ listing.content }}</p>
			<img width=320 height=320 src="{{ listing.image.url }}" />
          </div>
        </article>       
        {% endif %}

    {% endfor %}

{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>    
        <title>{% block title %}Auctions{% endblock %}</title>

         <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'auctions/styles.css' %}">
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                <img alt="wheel-cart-logo" src="media/logo.png" width="40" height="30" />
                <a class="navbar-brand mr-4" href="{% url 'index' %}">Commerce</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                    <a class="nav-item nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                      {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Log in as {{ request.user }}</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                      {% else %}
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                      {% endif %}
                    </div>
                </div>
                </div>
            </nav>
        </header>

            <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block body %}{% endblock body%}
        </div>
        <div class="col-md-4">
          <div class="content-section">
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="{% url 'index' %}">Latest Listings</a></li>

				<br />
                <li class="list-group-item list-group-item-light"><a href="{% url 'category' name='shoes' %}">Shoes</a></li>

                <li class="list-group-item list-group-item-light"><a href="{% url 'category' name='clothing' %}">Clothing</a></li>
                <li class="list-group-item list-group-item-light"><a href="{% url 'category' name='accessories' %}">Accessories</a></li>
                <li class="list-group-item list-group-item-light"><a href="{% url 'category' name='other' %}">Other</a></li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<article class="media content-section">
    <div class="media-body">
    <div class="article-metadata">
        <a class="mr-2" href="#">{{ listing.author }}</a>
        <small class="text-muted">{{ listing.date|date:"F d, Y" }}</small>
        <small class="ml-3">Price: <b>${{ listing.price }}</b></small>

    </div>
    <h2><a class="article-title" href="#">{{ listing.title }}</a></h2>
    <p class="article-content">{{ listing.content }}</p>
    <img width=320 height=320 src="{{ listing.image.url }}" />
    <br />
    <form action="add_to_watchlist" method="POST">
        {% csrf_token %}
        <button class="btn btn-info small mt-3">Add to watchlist</button>
        <input type="hidden" name="id" value="{{ listing.id }}" />
    </form>

    {% if not listing.author.id == user.id %}
        <form action="bid" method="POST">
            {% csrf_token %}
            <hr />
            <h3>Bid</h3>
            <div class="form-group">
                <input class="form-control" type="number" name="bid" placeholder="bid">
                <input type="hidden" name="id" value="{{ listing.id }}" />
                <button class="btn btn-info small mt-3">Bid</button>
            </div>
        </form>
    {% endif %}

    {% if listing.author.id == user.id %}
        <form action="bid_options" method="POST">
            {% csrf_token %}
            <hr />
            <div class="form-group">
            <p>Bidding options</p>
                <select id="most-like" name="option" class="form-control" required>
                    <option  selected value>Select an option</option>
                    <option value="False">Open</option>
                    <option value="True">Close</option>
                </select>
                <input type="hidden" name="id" value="{{ listing.id }}" />
                <button class="btn btn-info small mt-3">Submit</button>
            </div>
        </form>
    </div>
    {% endif %}
</article>

<h2>Comments</h2>
<hr />
<form method="POST" action="{% url 'listing_detail' listing.id %}">
    {% csrf_token %}
    {{ commentForm|crispy }}
    <button class="btn btn-info small mt-3">Add</button>
</form>
<hr />
{% for comment in comments %}
    <article class="media content-section">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ comment.author }}</a>
            <small class="text-muted">{{ comment.created_at|date:"F d, Y" }}</small>
            <!-- <small class="ml-3">Price: <b>${{ listing.price }}</b></small> -->
            <!-- {{ person.get_gender_display }} -->
            <!-- <small class="ml-3">Category: <b>{{ listing.get_listing_categories_display }}</b></small> -->
        </div>
        <p class="article-content">{{ comment.content }}</p>
        </div>
    </article>
{% endfor %}

{% endblock body %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/profile.html
{% extends 'auctions/layout.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" />
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
</div>


 {% for listing in listings %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ listing.author }}</a>
              <small class="text-muted">{{ listing.date|date:"F d, Y" }}</small>
              <small class="ml-3">Price: <b>${{ listing.price }}</b></small>
              <!-- {{ person.get_gender_display }} -->
              <small class="ml-3">Category: <b>{{ listing.get_listing_categories_display }}</b></small>
            </div>
            <h2><a class="article-title" href="{% url 'listing_detail' pk=listing.pk %}">{{ listing.title }}</a></h2>
            <p class="article-content">{{ listing.content }}</p>
			<img width=320 height=320 src="{{ listing.image.url }}" />
          </div>
        </article>
{% endfor %}


{% endblock body %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" />
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
</div>

{% for item in watchlist %}
    <article class="media content-section">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ item.listing.author }}</a>
                <small class="text-muted">{{ item.listing.date|date:"F d, Y" }}</small>
                <small class="ml-3">Price: <b>99$</b></small>
            </div>
            <h2><a class="article-title" href="{% url 'listing_detail' item.listing.id %}">{{ item.listing.title }}</a></h2>
            <p class="article-content">{{ listing.content }}</p>
            <img width=320 height=320 src="{{ item.listing.image.url }}" />
            <br />
            <form action="remove_from_watchlist" method="POST">
                {% csrf_token %}
                <button class="btn btn-info small mt-3">Remove from watchlist</button>
                <input type="hidden" name="id" value="{{ item.id }}" />
            </form>
            </div>
    </article>
{% endfor %}

{% endblock body %}